version: '3.1'

services:
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      - POSTGRES_DB=warehouse
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - ${BOT_DB_PORT:-5432}:5432
volumes:
  db_data:

